### PR TITLE
adding a cmd line option for a custom "remote" card provider with a TerminalFactory

### PR DESCRIPTION
**Pull request by dancvrcek**

### CODE REVIEW

**Comment by martinpaljak** [comment]
Thanks for the PR!

So I'd split this into two:

- What is currently missing 100%: `--providerarg` (some better name?) for existing `--provider` option (where new/modifiable implementations actually could also use environment variables or configuration files). Probably arguments are of type `String` ?

- cmdline-fu sugar for not being forced to add the provider jar to the classpath manually, as currently is explained in the README. DWIM would mandate that `--provider` should recognize the `jar:class` construct, which seems reasonable (nothing else "standard" comes to mind). Maybe even `jar:class:arg`

Thanks for the input, I'll implement this slightly differently as explained, would that cover your needs?

**Comment by dancvrcek** [comment]
Hi Martin

that sounds good.  I think it should work.

I like the jar:class:arg - I like it more than 2 apduj4 parameters I
suggested originally. In fact calling getRemoteTerminalFactory() (as
named now) would just change the source of its last argument.

Dan

**Comment by dancvrcek** [comment]
Random topic. We also need 2-3 more features:
1.  "production" - this will make sure that no sensitive information -
i.e., OP keys are displayed
2. "dualcontrol" - that will allow entering and reconstructing OP keys
from components (2 or 3)
3. "kcv" - key entry control - protection from typos when entering OP keys

If it's ok, I would do the first version once this pull request is dealt
with.

Dan

**Comment by martinpaljak** [comment]
Please bring this over to GP tracker and make separate tickets. I'll post the replies there.

**Comment by dancvrcek** [comment]
shall I try to get the implementation closer to what we discussed or are you working on this?

**Comment by martinpaljak** [comment]
I'll not be working on this before a week or two, feel free to hack on.

**Comment by martinpaljak** [comment]
I'll commit this as soon as I have a "somewhat sensible" fuzzing provider inside apdu4j (which is the only use case for an external provider in a JAR with parameters I could think out at once for GPPro)

**Comment by martinpaljak** [comment]
v0.0.33 adds `-provider` handling. The format is `jar:class:args` and args should be urlencoded if it contains `:` characters. Some "sensible defaults" are possible, as described in the code: https://github.com/martinpaljak/apdu4j/blob/master/src/apdu4j/TerminalManager.java#L184 Have a look if this is what you need. I'll add a fuzzing provider to apdu4j at some point, what allows to do simple testing of existing code, such as GPPro.

**Pull request closed without merging**
