### PR TITLE
Add ETSI get more data tag

### PR DESCRIPTION
**Pull request by xavo95**

### CODE REVIEW

**Comment by xavo95** [comment]
Providing support for get more data in the case of ETSI(Talking with UICC/SIM instead of tipical Global Platform compliant card)

**Comment by martinpaljak** [comment]
Could you add this as a standalone wrapper class?

**Comment by xavo95** [comment]
Hello
Sorry I forgot about this pull request. But I would be willing to work on it.
Is it still not integrated?

Regards

**Comment by martinpaljak** [comment]
https://github.com/martinpaljak/apdu4j/blob/master/core/src/main/java/apdu4j/GetMoreDataWrapper.java

**Pull request closed without merging**
